# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161716)
$foreground = rgb(D9D8D7)
$color0 = rgb(3D3E3D)
$color1 = rgb(0D120F)
$color2 = rgb(0D120F)
$color3 = rgb(27302D)
$color4 = rgb(4F3C36)
$color5 = rgb(4F3C36)
$color6 = rgb(6F6C69)
$color7 = rgb(C1BFBD)
$color8 = rgb(878684)
$color9 = rgb(121814)
$color10 = rgb(121814)
$color11 = rgb(34403C)
$color12 = rgb(695048)
$color13 = rgb(695048)
$color14 = rgb(94908C)
$color15 = rgb(C1BFBD)
