# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D9D8D7
background         #161716
cursor             #767875

active_tab_foreground     #161716
active_tab_background     #D9D8D7
inactive_tab_foreground   #D9D8D7
inactive_tab_background   #161716

active_border_color   #D9D8D7
inactive_border_color #161716
bell_border_color     #0D120F

color0      #3D3E3D
color1		#0D120F
color2		#0D120F
color3		#27302D
color4		#4F3C36
color5		#4F3C36
color6		#6F6C69
color7		#C1BFBD
color8		#878684
color9		#121814
color10		#121814
color11		#34403C
color12		#695048
color13		#695048
color14		#94908C
color15		#C1BFBD
